export const provincias = [
	{ "nombre": "Álava" },
	{ "nombre": "Albacete" },
	{ "nombre": "Alicante" },
	{ "nombre": "Almería" },
	{ "nombre": "Asturias" },
	{ "nombre": "Ávila" },
	{ "nombre": "Badajoz" },
	{ "nombre": "Barcelona" },
	{ "nombre": "Burgos" },
	{ "nombre": "Cáceres" },
	{ "nombre": "Cádiz" },
	{ "nombre": "Cantabria" },
	{ "nombre": "Castellón" },
	{ "nombre": "Ciudad Real" },
	{ "nombre": "Córdoba" },
	{ "nombre": "La Coruña" },
	{ "nombre": "Cuenca" },
	{ "nombre": "Gerona" },
	{ "nombre": "Granada" },
	{ "nombre": "Guadalajara" },
	{ "nombre": "Guipúzcoa" },
	{ "nombre": "Huelva" },
	{ "nombre": "Huesca" },
	{ "nombre": "Islas Baleares" },
	{ "nombre": "Jaén" },
	{ "nombre": "La Rioja" },
	{ "nombre": "Las Palmas" },
	{ "nombre": "León" },
	{ "nombre": "Lérida" },
	{ "nombre": "Lugo" },
	{ "nombre": "Madrid" },
	{ "nombre": "Málaga" },
	{ "nombre": "Murcia" },
	{ "nombre": "Navarra" },
	{ "nombre": "Orense" },
	{ "nombre": "Palencia" },
	{ "nombre": "Pontevedra" },
	{ "nombre": "Salamanca" },
	{ "nombre": "Santa Cruz de Tenerife" },
	{ "nombre": "Segovia" },
	{ "nombre": "Sevilla" },
	{ "nombre": "Soria" },
	{ "nombre": "Tarragona" },
	{ "nombre": "Teruel" },
	{ "nombre": "Toledo" },
	{ "nombre": "Valencia" },
	{ "nombre": "Valladolid" },
	{ "nombre": "Vizcaya" },
	{ "nombre": "Zamora" },
	{ "nombre": "Zaragoza" },
	{ "nombre": "Ceuta" },
	{ "nombre": "Melilla" }
];
